apiVersion: v1
kind: Secret
metadata:
  name: kraken-lab-secrets
type: Opaque
stringData:
  BEARER_PASSWORD: KrakenLabBearer-ChangeMe
  RORSCHACH_SECRET_EVEN: YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYQ
  RORSCHACH_SECRET_ODD: YmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYg
  KRAKEN_UI_PASSWORD_KEY: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
  KRAKEN_UI_SESSION_KEY: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWYwMTIzNDU2Nzg5YWJjZGVmMDEyMzQ1Njc4OWFiY2RlZg==
  KRAKEN_UI_ADMIN_PASSWORD: "Tentacle-Root!2026"
  KRAKEN_UI_OPERATOR_PASSWORD: "DeepCurrent!2026"
  KRAKEN_UI_AUDITOR_PASSWORD: "Audit-ReadOnly!2026"
